name: code-quality
on:
  push:
    branches:
      - main
  pull_request:

env:
  DO_NOT_TRACK: 1
#  TURBO_SCM_BASE: origin/${{ github.head_ref }}

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "head_ref: ${{ github.head_ref }}"

      - name: Prepare
        uses: ./.github/composite-actions/prepare

      - name: Run ESLint check
        run: |
          BASE_COMMAND="pnpm exec turbo run lint"
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            BASE_COMMAND="$BASE_COMMAND --affected"
          fi
          echo "Running: $BASE_COMMAND"
          $BASE_COMMAND
#        run: pnpm exec turbo run lint --affected

  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/composite-actions/prepare

      - name: Run type checks
        run: pnpm run typecheck

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/composite-actions/prepare

      - name: Run unit tests
        run: pnpm run test
